---
- name: install dependencies for building stress-ng
  yum: name=libattr-devel,keyutils-libs-devel,make,gcc,tar state=present

- name: install screen
  yum: name=screen state=present

- name: copy and extract stress-ng tarbalil
  unarchive: src=stress-ng-0.05.11.tar.gz dest="/root" copy=yes

- name: build stress-ng
  command: "make"
  args:
    chdir: '/root/stress-ng-0.05.11'
    creates: '/root/stress-ng-0.05.11/stress-ng'

- name: install stress-ng
  command: "make install"
  args:
    chdir: '/root/stress-ng-0.05.11'
    creates: '/usr/bin/stress-ng'

- name: create a temp dir for stress to use
  file: path=/root/stress-tmp state=directory

- name: run stress-ng
  command: >
    screen -S stress -d -m
    stress-ng
    --timeout {{test_duration}}
    --hdd-bytes {{bytes_per_hdd_worker}}
    --vm-bytes {{bytes_per_vm_worker}}
    --vm-method all
    --cpu-method all
    --cpu {{cpu_workers}}
    --vm {{vm_workers}}
    --hdd {{hdd_workers}}
  args:
    chdir: '/root/stress-tmp'
    creates: '/var/run/screen/S-root/*.stress'
